### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by sreenathsk** [ggerganov/ggwave#24]
Is there any javascript for android or can I find any source code for your Android app?
It will be very helpful to find one

**Comment by ggerganov** [comment]
I will definitely add an Android SDK with a few examples of how to use it. However, it might take some time to do it as I want to improve other things first and my Android experience is lacking. See #2 for more information - I will post updates there when I start working on it.

For now I don't plan to publish my Android project for the Waver app as it is a big mess with lots of manual tweaks.

**Comment by sreenathsk** [comment]
Ok Thankyou 😊

**Comment by ggerganov** [comment]
@commonsguy just posted an update with a sample Android project that you might want to take a look:

https://github.com/ggerganov/ggwave/issues/2#issuecomment-787134580

I will close this issue. If you have any additional questions, please post them in #2.
