### ISSUE TITLE
Soundless file

### ISSUE THREAD

**Issue by arthursady** [ggerganov/ggwave#45]
Hi, I might be misunderstanding how to use the library but regarding the ggwave-to-file the readme states that by using the following commands in the terminal we would be able to produce audible and ultrasound files. 

# audible example
curl -sS 'https://ggwave-to-file.ggerganov.com/?m=Hello world!' --output hello.wav

# ultrasound example
curl -sS 'https://ggwave-to-file.ggerganov.com/?m=Hello world!&p=4' --output hello.wav

When I run the ultrasound command with fast or fastest p codes. I still get a R2D2 like output sound in the audio. I was expecting that the file would contain just the inaudible frequencies that the phones would hear but we wouldn't.

I need to produce a file that I can merge into other sounds, so the inaudible property is really critical for me. Is it possible to generate audios without audible content to transmit the messages?

**Comment by arthursady** [comment]
I also downloaded ggwave-to-file built it locally and tried to generate files with different output sample rates by passing the -s parameter. I was able to reach all kinds of outputs from audible to inaudible but everytime I use the -s parameter the resulting audio file is not recognised on my hearing device. When I omit the -s and leave the default. The hearing device identifies the messages without any problems.

**Comment by ggerganov** [comment]
Hi, I just tried to run the commands that you have posted in your question and they work as expected.
The first command generates an audible "Hello World!" message using the `Fast` protocol.
The second command generates an ultrasound "Hello World!" message using the `[U] Fast` protocol.

The `-s` parameter changes the sample rate of the generated file.
For example, this command generates a `.wav` file at 24 kHz:

```
curl -sS 'https://ggwave-to-file.ggerganov.com/?m=Hello world!&s=24000' --output hello.wav
```

**Comment by arthursady** [comment]
@ggerganov as you said, the command really work for the audio. I was able to create inaudible files by changing frequencies and the file does seem to be changed accordingly.  
-
What is puzzling me right now is that I am using the android example in https://github.com/ggerganov/ggwave-java to test the file. What is happening is that if I generate the file without using the -s, the device is able to receive the message just right. But if I pass any value to the -s even 48000 which is the default, the device stops receiving the message when I run the audio file. I tried to go into the code and change the default frequencies both in the file generator and the java lib example but still had the same situation. The only configuration I was able to run correctly with the Android example was creating the file without the -s and without changing the code default frequency leaving it at 48000. Because of that I don't know if the problem is with the file generation or actually in the android example app decoding.
-
Would you have any guidance of what could be causing this? It has been a long time since I went deep into modulation and demodulation problems so I am without ideas of where I could look at to understand what is happening.
-
I apologise for bothering you with this and thank you for the previous reply.

**Comment by ggerganov** [comment]
I just tried generating a few messages using different sampling rates via the `-s` argument and the `ggwave-java` app successfully receives the messages. Not sure what could be causing the issue that you observe.

Can you provide a step-by-step process that fails for you? The exact commands that you execute.
Make sure to use the original `ggwave-java` project without any modifications.

> I apologise for bothering you with this and thank you for the previous reply.

No problems at all - I will be glad to help if I can!

**Comment by arthursady** [comment]
@ggerganov thank you.

So, the situation I went through was basically cloning ggwave on this commit fbd51eb2466ec5699ed6296f25d06d2094d9e77b which seems to be the latest in the master branch. Then I went through the setup of ggwave-to-file. Setup seemed to work as I was able to start creating audio files as intended so I went and cloned ggwave-java on this commit 211ae947fda7307aa318cd430216bcabd9b8d071 which also seemed to be the latest. 

Then I installed the Android app in a real test device I have here and was able to parse multiple audios that I created with only the -p5 command. Since that worked I moved to the next step.

I basically wanted to achieve a soundless file so that I could mix it into other sounds like musics. So I started changing the properties of the audio file generation. The first thing I tried was to change the -s frequency. However, when I do, the app wasn't able to parse any audios. I tried increasing the frequency from 48k to several values up to 96k and I also tried to decrease to several values down to 24k but none of those tests worked. The only situation in which the app was able to parse the texts was when I generated the audio files using only the message and -p command. I also had the same result using the endpoint the library provides for audio generation.

Up to this point I was testing without changing any code. But then I started trying to understand a bit better if there were any parameters I could try changing. So far I wasn't successful though.

I am not sure if I am pursuing the right way to make the audios soundless, after I checking in the readme that the base frequency used on the protocols is 15k, I considered if changing that to something like 19k could work but I didn't find any way to test that theory.

**Comment by ggerganov** [comment]
Thanks for the description.
I am still not sure what could be the problem.

I played a bit with this idea and i found a way to embed ultrasound audio messages into existing audio.
Here are the steps:

- Start with some audio file `clip.mp3` in which you want to add an ultrasound message
- Convert it to `.mp4`:
  ```
  ffmpeg -i clip.mp3 clip.mp4
  ```
- Here is one example that I took from the internet:

https://user-images.githubusercontent.com/1991296/130362630-ac429515-0ee6-4317-9331-cd5b4fa168a1.mp4

- Generate the ultrasound message. For example:

  ```
  curl -sS 'https://ggwave-to-file.ggerganov.com/?m=My message&p=3' --output msg.wav
  ```

- No need to change the `-s` parameter. I tried changing it to `96000` and it still works, but for ultrasound, the default `48000` should be just fine. This is the sample rate, not the frequency as you mentioned.
- Convert the `msg.wav` to `msg.mp4`:

  ```
  ffmpeg -i msg.wav -b:a 320k -q:a 0 -ar 48000 msg.mp4
  ```

https://user-images.githubusercontent.com/1991296/130363120-09ed624b-089b-4a93-94bd-c5050f6f2abf.mp4

 - Mix the ultrasound message in the original audio file:

  ```
  ffmpeg -i clip.mp4 -i msg.mp4 -filter_complex "[0]volume=2.0[a];[1]adelay=5000,volume=2.0[b];[a][b]amix=inputs=2:dropout_transition=999999[c]" -map "[c]" -c:v copy -b:a 320k -q:a 0 -ar 48000 clip_with_message.mp4
  ```

https://user-images.githubusercontent.com/1991296/130362764-0fdae6d2-ea92-4be3-8c09-e4f937fb15f1.mp4

- At around 5 second into the playback, you should be able to receive the ultrasound message. I tested both with the Waver app and the `ggwave-java` app

Hope this helps.

**Comment by arthursady** [comment]
@ggerganov thank you for the amazing response. It does help.
