### ISSUE TITLE
C library ggwave_decode: logging of binary data

### ISSUE THREAD

**Issue by gizahNL** [ggerganov/ggwave#51]
The ggwave library does logging via printf by default. And will print out the data it has received as if it is text. When sending binary data this can lead to corrupted terminals as some binary data can be interpreted as control characters.

Suggested fix:
-allow disabling of logging altogether
-ideally: don't log via printf, instead allow calling applications to configure logging via their own callbacks.
-make no assumptions about the data, blindly printing the data (except perhaps under a debug log level) can lead to unintended behavior.

**Comment by ggerganov** [comment]
I just opened #52 - let me know if you have any comments on the proposed interface

**Comment by gizahNL** [comment]
left some nits, otherwise it's great :)

Nice to haves in the future might be, depending on how much logging you'll add (from my experience in our application its 1 line per decoded message),  log levels + filtering, and perhaps a callback that takes at least the level logmsg (or varargs)  and a user defined pointer var.
