### ISSUE TITLE
Arduino example arduino-tx cant compile: undefined reference to `GGWave::Protocols::kDefault()::data'

### ISSUE THREAD

**Issue by fl0wtec** [ggerganov/ggwave#72]
Dear Georgi,

I can´t get the arduino-tx example to compile. All necessary files seem to be in place, but its complaining about not having a reference to **GGWave::Protocols::kDefault()::data**.
Compile log error:

```
C:\Users\fl0wtec\AppData\Local\Temp\arduino_build_838640\sketch\src\ggwave.cpp.o:(.rodata+0x0): undefined reference to `GGWave::Protocols::kDefault()::data'
C:\Users\fl0wtec\AppData\Local\Temp\arduino_build_838640\sketch\src\ggwave.cpp.o:(.rodata+0xc): undefined reference to `GGWave::Protocols::kDefault()::data'
C:\Users\fl0wtec\AppData\Local\Temp\arduino_build_838640\sketch\src\ggwave.cpp.o:(.rodata+0x18): undefined reference to `GGWave::Protocols::kDefault()::data'
C:\Users\fl0wtec\AppData\Local\Temp\arduino_build_838640\sketch\src\ggwave.cpp.o:(.rodata+0x24): undefined reference to `GGWave::Protocols::kDefault()::data'
C:\Users\fl0wtec\AppData\Local\Temp\arduino_build_838640\sketch\src\ggwave.cpp.o:(.rodata+0x30): undefined reference to `GGWave::Protocols::kDefault()::data'
C:\Users\fl0wtec\AppData\Local\Temp\arduino_build_838640\sketch\src\ggwave.cpp.o:(.rodata+0x3c): undefined reference to `GGWave::Protocols::kDefault()::data'
collect2.exe: error: ld returned 1 exit status
```

Is this reference indeed missing or am I doing anything wrong?
This is the file/folder structure I´m working with:
![image](https://user-images.githubusercontent.com/29065998/180066598-1f5e5ba1-36c0-4a32-bbd4-37ca6b312cf3.png)

Thanks & Best regards
fl0wtec

**Comment by fl0wtec** [comment]
Dear Georgi
thanks for the quick and comprehensive reply! This worked like a charm.
I forgot to mention, that I tested compiling with the [`ggwave-ggwave-v0.4.0`](https://github.com/ggerganov/ggwave/releases/tag/ggwave-v0.4.0) version.

I´ve switched both `ggwave.h` and `ggwave.cpp` for the master branch versions.

Now the Arduino IDE compiles flawlessly.

Thanks and best regards!

**Comment by fl0wtec** [comment]
Closing the issue as it has been solved by using ggwave.h and ggwave.cpp from the main branch.

**Comment by ggerganov** [comment]
Glad that it works now!

Btw, I have also updated the Arduino examples on the `master` branch, so if you experience any problems with the data transmission, make sure to use the latest sketches. And feel free to open another issue if you have any problems with using the library.
